[package]
name = "phoenix_uefi_std"
version = "0.1.5"
edition = "2021"
description = "UEFI standard library"


[lib]
name = "uefi_std"

[dependencies]
phoenix-uefi = {git = "https://github.com/JakubGawron1/UEFI"}
phoenix_uefi_alloc = {git = "https://github.com/JakubGawron1/uefi-alloc"}